// Permission constants (similar to Discord)
// This file can be imported in both client and server code
export const PERMISSIONS = {
  // General permissions
  ADMINISTRATOR: "ADMINISTRATOR",
  VIEW_CHANNELS: "VIEW_CHANNELS",
  MANAGE_CHANNELS: "MANAGE_CHANNELS",
  MANAGE_ROLES: "MANAGE_ROLES",
  MANAGE_SERVER: "MANAGE_SERVER",
  MANAGE_MESSAGES: "MANAGE_MESSAGES",
  MANAGE_MEMBERS: "MANAGE_MEMBERS",
  
  // Channel permissions
  SEND_MESSAGES: "SEND_MESSAGES",
  SEND_TTS_MESSAGES: "SEND_TTS_MESSAGES",
  EMBED_LINKS: "EMBED_LINKS",
  ATTACH_FILES: "ATTACH_FILES",
  READ_MESSAGE_HISTORY: "READ_MESSAGE_HISTORY",
  MENTION_EVERYONE: "MENTION_EVERYONE",
  USE_EXTERNAL_EMOJIS: "USE_EXTERNAL_EMOJIS",
  ADD_REACTIONS: "ADD_REACTIONS",
  
  // Voice permissions
  CONNECT: "CONNECT",
  SPEAK: "SPEAK",
  MUTE_MEMBERS: "MUTE_MEMBERS",
  DEAFEN_MEMBERS: "DEAFEN_MEMBERS",
  MOVE_MEMBERS: "MOVE_MEMBERS",
  USE_VAD: "USE_VAD",
  
  // Other
  CHANGE_NICKNAME: "CHANGE_NICKNAME",
  MANAGE_NICKNAMES: "MANAGE_NICKNAMES",
  KICK_MEMBERS: "KICK_MEMBERS",
  BAN_MEMBERS: "BAN_MEMBERS",
} as const;


